version: '3.7'

services:

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
    - ./mongo-volume/data/db

  todo-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo